[package]
name = "firestore-emulator"
version = { workspace = true }
edition = "2021"

[features]
default = ["ui"]

# The console feature enables the use of the tokio console for runtime insight in async behavior.
console = ["dep:console", "dep:console-subscriber", "dep:tracing-subscriber"]

# The tracing feature enables tracing logging to stdout.
tracing = [
    "dep:time",
    "tracing-subscriber/local-time",
    "tracing-subscriber/env-filter",
]

# Enable the web interface on the same host:port as the other emulator endpoints
ui = ["emulator-ui/ui"]

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
async-trait = "0.1.77"
axum = "0.6.20"
firestore-database = { path = "crates/firestore-database" }
futures = "0.3.30"
googleapis = { path = "crates/googleapis" }
hyper = "0.14"
itertools = "0.12.1"
pin-project = "1.1.5"
prost = "0.12"
serde = "1.0.197"
serde_with = "3.6.1"
thiserror = "1.0.57"
time = "0.3.34"
tokio = "1.36.0"
tokio-stream = "0.1.14"
tonic = "0.11"
tower = "0.4.13"
tracing = "0.1.40"

[dependencies]
axum = { workspace = true }
clap = { version = "4.5.1", features = ["derive", "env"] }
color-eyre = "0.6.2"
console = { version = "0.15.8", optional = true }
console-subscriber = { version = "0.2.0", optional = true }
emulator-grpc = { path = "crates/emulator-grpc" }
emulator-ui = { path = "crates/emulator-ui" }
hybrid-axum-tonic = { path = "crates/hybrid-axum-tonic" }
tikv-jemallocator = "0.5.4"
time = { workspace = true, optional = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.18", optional = true }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
