[package]
name = "firestore-emulator"
version = "0.1.0"
edition = "2021"

[features]
default = []
console = ["dep:console", "dep:console-subscriber", "dep:tracing-subscriber"]
tracing = [
    "dep:time",
    "tracing-subscriber/local-time",
    "tracing-subscriber/env-filter",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive", "env"] }
color-eyre = "0.6.2"
console = { version = "0.15.7", optional = true }
console-subscriber = { version = "0.2.0", optional = true }
futures = "0.3.29"
itertools = "0.12.0"
prost = "0.12"
prost-types = "0.12"
string_cache = "0.8.7"
tikv-jemallocator = "0.5.4"
time = { version = "0.3.30", features = [
    "formatting",
    "macros",
], optional = true }
tokio = { version = "1.34.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["full"] }
tonic = { version = "0.10", features = ["gzip"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", optional = true }

[build-dependencies]
tonic-build = "0.10"

# [profile.release]
# opt-level = 3
# lto = true
