[package]
name = "firestore-emulator"
description = "Google Cloud Firestore emulator with focus on stability"
version = { workspace = true }
edition = "2021"

[features]
default = ["ui"]

# The console feature enables the use of the tokio console for runtime insight in async behavior.
console = ["emulator-tracing/console"]

# Enable the web interface on the same host:port as the other emulator endpoints
ui = ["emulator-http/ui"]

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.1"

[workspace.dependencies]
async-trait = "0.1.80"
axum = "0.6.20"
clap = "4.5.7"
color-eyre = "0.6.3"
console-subscriber = "0.3.0"
ctreg = "1.0.2"
futures = "0.3.30"
hyper = "0.14"
itertools = "0.13.0"
once_cell = "1.19.0"
pin-project = "1.1.5"
prost = "0.12"
rstest = "0.21.0"
serde = "1.0.203"
serde_json = "1.0.117"
serde_with = "3.8.1"
string_cache = "0.8.7"
thiserror = "1.0.61"
tikv-jemallocator = "0.5.4"
time = "0.3.36"
tokio = "1.38.0"
tokio-stream = "0.1.15"
tonic = "0.11"
tonic-build = "0.11"
tower = "0.4.13"
tower-http = "0.4.4"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[workspace.lints.rust]
unsafe_code = "forbid"
explicit_outlives_requirements = "forbid"
let_underscore_drop = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
non_ascii_idents = "forbid"
single_use_lifetimes = "warn"
unit_bindings = "warn"
unreachable_pub = "warn"
unused_crate_dependencies = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
# Until this is resolved: https://github.com/rust-lang/rust-clippy/issues/12281
blocks_in_conditions = "allow"

[dependencies]
axum = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
color-eyre = { workspace = true }
emulator-database = { path = "crates/emulator-database" }
emulator-grpc = { path = "crates/emulator-grpc" }
emulator-http = { path = "crates/emulator-http" }
emulator-tracing = { path = "crates/emulator-tracing" }
hybrid-axum-tonic = { path = "crates/hybrid-axum-tonic" }
tikv-jemallocator = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { workspace = true }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
