edition = "2021"
version = "Two"

# Allow rustfmt to format our doc comments, such an awesome feature 😍
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true

# Prefer to use field init shorthands, e.g. `Struct { field }` instead of `Struct { field: field }`
use_field_init_shorthand = true

# Align enum and their "value" and struct fields and their types in a table (max extra padding of 5 spaces)
enum_discrim_align_threshold = 5
struct_field_align_threshold = 5


# max_width = 100
# use_small_heuristics = "Max"
# single_line_let_else_max_width = 99

# format_macro_matchers = true
# format_strings = true
# group_imports = "StdExternalCrate"
# imports_granularity = "Crate"
