[package]
name = "googleapis"
edition = "2021"

[lib]
doctest = false

[dependencies]
chrono = { version = "0.4.34", default-features = false, features = ["now"] }
prost.workspace = true
thiserror = "1.0.57"
tonic.workspace = true

[build-dependencies]
tonic-build = "0.11"

[dev-dependencies]
itertools = "0.12.1"
