[package]
name = "emulator-http"
version = { workspace = true }
edition = "2021"

[features]
default = []

# Enable the web interface on the same host:port as the other emulator endpoints
ui = []

[dependencies]
axum = { workspace = true, features = ["ws"] }
emulator-database = { path = "../emulator-database" }
emulator-tracing = { path = "../emulator-tracing" }
serde_json = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[lints]
workspace = true
