[package]
name = "emulator-http"
version = { workspace = true }
edition = "2021"

[features]
default = []

# Enable the web interface on the same host:port as the other emulator endpoints
ui = []

[dependencies]
axum = { workspace = true, features = ["macros"] }
emulator-tracing = { path = "../emulator-tracing" }
firestore-database = { path = "../firestore-database" }
serde_json = { workspace = true }
tower-http = { workspace = true, features = ["full"] }

[lints]
workspace = true
